Taydev
taylor-c-williams/backend-hand-of-resources pull request #1
Opened 2022-01-27 23:33 UTC by taylor-c-williams

2022-01-27 23:42 UTC, taylor-c-williams commented
https://dry-reaches-76258.herokuapp.com/api/v1/spiceupyourlife/melb
https://dry-reaches-76258.herokuapp.com/api/v1/spiceupyourlife/emma
https://dry-reaches-76258.herokuapp.com/api/v1/spiceupyourlife/melaniec
https://dry-reaches-76258.herokuapp.com/api/v1/spiceupyourlife/victoria

2022-02-01 20:46 UTC, erichsauer requested changes
love the fake stagenames 😂

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Emma.test.js
> +    const emma = await Emma.insert({ name:'Emma Lee Bunton', stagename:'Baby Spice', birthdate:'1/21/1976' });
looking for an endpoint test here, so `const emma = await request(app).post( ...` rather than `Emma.insert`

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Geri.test.js
> +    const geri = await Geri.insert({ name:'Geraldine Estelle Halliwell', stagename:'Ginger Spice', birthdate:'8/6/1972' });
see emma

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Melaniec.test.js
> +    const melaniec = await Melaniec.insert({ name:'Melanie Jayne Chisholm', stagename:'Sporty Spice', birthdate:'1/12/1974' });
see emma

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Melb.test.js
> +    const mel = await Melb.insert({ name:'Melanie Janine Brown', stagename:'Scary Spice', birthdate:'5/29/1975' });
see emma

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Victoria.test.js
> +    const victoria = await Victoria.insert({ name:'Victoria Caroline Adams', stagename:'Posh Spice', birthdate:'4/17/1974' });
see emma

2022-02-01 20:46 UTC, erichsauer commented on lib/controllers/melaniecs.js
> +
looking for `.patch` & `.delete` routes here

2022-02-01 20:46 UTC, erichsauer commented on lib/controllers/geris.js
> +
looking for `.patch` & `.delete` routes here

2022-02-01 20:46 UTC, erichsauer commented on lib/models/Geri.js
> +
missing `update` and `delete` methods

2022-02-01 20:46 UTC, erichsauer commented on lib/models/Melaniec.js
> +
missing `update` and `delete` methods

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Melaniec.test.js
> +
looking for .patch & .delete tests here

2022-02-01 20:46 UTC, erichsauer commented on __tests__/Geri.test.js
> +
looking for .patch & .delete tests here

2022-02-01 20:49 UTC, taylor-c-williams commented
Haha ty ty for noticing. And yes, I only realized yesterday while writing
the backend-sql project that those tests aren’t… doing anything lol. Will
resub, thanks!

On Tue, Feb 1, 2022 at 12:46 PM Erich Sauer ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> love the fake stagenames 😂
> ------------------------------
>
> In __tests__/Emma.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796998146>
> :
>
> > +const setup = require('../data/setup');
>
> +const app = require('../lib/app');
>
> +const request = require('supertest');
>
> +const Emma = require('../lib/models/Emma');
>
> +
>
> +describe('Emma Routes', () => {
>
> +  beforeEach(() => {
>
> +    return setup(pool);
>
> +  });
>
> +
>
> +  afterAll(() => {
>
> +    pool.end();
>
> +  });
>
> +
>
> +  it('creates an Emma entry', async () => {
>
> +    const emma = await Emma.insert({ name:'Emma Lee Bunton', stagename:'Baby Spice', birthdate:'1/21/1976' });
>
>
> looking for an endpoint test here, so const emma = await
> request(app).post( ... rather than Emma.insert
> ------------------------------
>
> In __tests__/Geri.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796998334>
> :
>
> > +const setup = require('../data/setup');
>
> +const app = require('../lib/app');
>
> +const request = require('supertest');
>
> +const Geri = require('../lib/models/Geri');
>
> +
>
> +describe('Geri Routes', () => {
>
> +  beforeEach(() => {
>
> +    return setup(pool);
>
> +  });
>
> +
>
> +  afterAll(() => {
>
> +    pool.end();
>
> +  });
>
> +
>
> +  it('creates a Geri entry', async () => {
>
> +    const geri = await Geri.insert({ name:'Geraldine Estelle Halliwell', stagename:'Ginger Spice', birthdate:'8/6/1972' });
>
>
> see emma
> ------------------------------
>
> In __tests__/Melaniec.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796998470>
> :
>
> > +const setup = require('../data/setup');
>
> +const app = require('../lib/app');
>
> +const request = require('supertest');
>
> +const Melaniec = require('../lib/models/Melaniec');
>
> +
>
> +describe('Melanie C. Routes', () => {
>
> +  beforeEach(() => {
>
> +    return setup(pool);
>
> +  });
>
> +
>
> +  afterAll(() => {
>
> +    pool.end();
>
> +  });
>
> +
>
> +  it('creates a Melanie C. entry', async () => {
>
> +    const melaniec = await Melaniec.insert({ name:'Melanie Jayne Chisholm', stagename:'Sporty Spice', birthdate:'1/12/1974' });
>
>
> see emma
> ------------------------------
>
> In __tests__/Melb.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796998606>
> :
>
> > +const setup = require('../data/setup');
>
> +const app = require('../lib/app');
>
> +const Melb = require('../lib/models/Melb');
>
> +const request = require('supertest');
>
> +
>
> +describe('Melanie B routes', () => {
>
> +  beforeEach(() => {
>
> +    return setup(pool);
>
> +  });
>
> +
>
> +  afterAll(() => {
>
> +    pool.end();
>
> +  });
>
> +
>
> +  it('creates a Mel B. entry ', async () => {
>
> +    const mel = await Melb.insert({ name:'Melanie Janine Brown', stagename:'Scary Spice', birthdate:'5/29/1975' });
>
>
> see emma
> ------------------------------
>
> In __tests__/Victoria.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796998726>
> :
>
> > +const setup = require('../data/setup');
>
> +const app = require('../lib/app');
>
> +const request = require('supertest');
>
> +const Victoria = require('../lib/models/Victoria');
>
> +
>
> +describe('Victoria Routes', () => {
>
> +  beforeEach(() => {
>
> +    return setup(pool);
>
> +  });
>
> +
>
> +  afterAll(() => {
>
> +    pool.end();
>
> +  });
>
> +
>
> +  it('creates a Victoria entry', async () => {
>
> +    const victoria = await Victoria.insert({ name:'Victoria Caroline Adams', stagename:'Posh Spice', birthdate:'4/17/1974' });
>
>
> see emma
> ------------------------------
>
> In lib/controllers/melaniecs.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r796999920>
> :
>
> > +      birthdate: req.body.birthdate
>
> +    });
>
> +    res.json(melaniec);
>
> +  })
>
> +
>
> +  .get('/', async (req, res) => {
>
> +    const melaniec = await Melaniec.getAll();
>
> +    res.json(melaniec);
>
> +  })
>
> +
>
> +  .get('/:id', async (req, res) => {
>
> +    const { id } = req.params;
>
> +    const melaniec = await Melaniec.getById(id);
>
> +    res.json(melaniec);
>
> +  })
>
> +
>
>
> looking for .patch & .delete routes here
> ------------------------------
>
> In lib/controllers/geris.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r797000069>
> :
>
> > +      birthdate: req.body.birthdate
>
> +    });
>
> +    res.json(geri);
>
> +  })
>
> +
>
> +  .get('/', async(req, res) => {
>
> +    const geri = await Geri.getAll();
>
> +    res.json(geri);
>
> +  })
>
> +
>
> +  .get('/:id', async (req, res) => {
>
> +    const { id } = req.params;
>
> +    const geri = await Geri.getById(id);
>
> +    res.json(geri);
>
> +  })
>
> +
>
>
> looking for .patch & .delete routes here
> ------------------------------
>
> In lib/models/Geri.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r797000915>
> :
>
> > +      [name, stagename, birthdate]
>
> +    );
>
> +    return new Geri(rows[0]);
>
> +  }
>
> +
>
> +  static async getAll(){
>
> +    const { rows } = await pool.query('SELECT * FROM geri');
>
> +    return rows.map((row) => new Geri(row));
>
> +  }
>
> +
>
> +  static async getById(id) {
>
> +    const { rows } = await pool.query('SELECT * FROM geri WHERE id=$1', [id]);
>
> +    if (!rows[0]) return null;
>
> +    return new Geri(rows[0]);
>
> +  }
>
> +
>
>
> missing update and delete methods
> ------------------------------
>
> In lib/models/Melaniec.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r797001183>
> :
>
> > +    );
>
> +    return new Melaniec(rows[0]);
>
> +  }
>
> +
>
> +  static async getAll(){
>
> +    const { rows } = await pool.query('SELECT * FROM melaniec');
>
> +    return rows.map((row) => new Melaniec(row));
>
> +  }
>
> +
>
> +  static async getById(id) {
>
> +    const { rows } = await pool.query('SELECT * FROM melaniec WHERE id=$1', [id]);
>
> +    if (!rows[0]) return null;
>
> +    return new Melaniec(rows[0]);
>
> +  }
>
> +
>
> +
>
>
> missing update and delete methods
> ------------------------------
>
> In __tests__/Melaniec.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r797001691>
> :
>
> > +    const realMelaniec = await Melaniec.insert({ name:'Melanie Jayne Chisholm', stagename: 'Sporty Spice', birthdate:'1/12/1974' });
>
> +
>
> +    const fakeMelaniec = await Melaniec.insert({ name: 'Fake Melanie', stagename: 'Stubby Spice', birthdate: '1/22/2076' });
>
> +
>
> +    const res = await request(app).get('/api/v1/spiceupyourlife/melaniec');
>
> +    expect(res.body).toEqual([realMelaniec, fakeMelaniec]);
>
> +  });
>
> +
>
> +  it ('fetches a single Melanie C. by her ID', async () => {
>
> +    const melaniec = await Melaniec.insert({ name: 'Melanie J. Chisholm', stagename: 'Sporty Spice', birthdate:'1/12/1974' });
>
> +
>
> +    const res = await request(app).get(`/api/v1/spiceupyourlife/melaniec/${melaniec.id}`);
>
> +
>
> +    expect(res.body).toEqual(melaniec);
>
> +  });
>
> +
>
>
> looking for .patch & .delete tests here
> ------------------------------
>
> In __tests__/Geri.test.js
> <https://github.com/taylor-c-williams/backend-hand-of-resources/pull/1#discussion_r797001876>
> :
>
> > +    const realGeri = await Geri.insert({ name:'Geraldine Estelle Halliwell', stagename:'Ginger Spice', birthdate:'8/6/1972' });
>
> +
>
> +    const fakeGeri = await Geri.insert({ name: 'Fake Geri', stagename: 'Grubby Spice', birthdate: '1/22/4276 [...]

2022-02-07 05:10 UTC, merged